### ISSUE TITLE
Implement User Roles and Permissions

### ISSUE THREAD

**Issue by TrungMa1** [Lucia560/SpringBoot_Labb2#26]
Define different roles for users, such as admin and regular user, to manage access to various features within the application. This feature will restrict certain functionalities based on user roles, for example, only administrators can delete messages.

- Define user roles, such as admin and regular user.
- Implement role-based access control (RBAC) to restrict access to certain functionalities.
- Create authorization logic to enforce permissions based on user roles.
- Ensure that only users with the appropriate role can perform specific actions, such as deleting messages.

**Comment by Lucia560** [comment]
We agreed that we will not have admin , just user .
